# Étape 1: Choisir une image de base avec Python 3.9
FROM python:3.9-slim-buster

# Définir le répertoire de travail dans le conteneur
WORKDIR /opt/airflow

# Étape 2: Installer Airflow (ajustez à la version souhaitée)
RUN pip install apache-airflow==2.3.0 --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.3.0/constraints-3.9.txt"

# Étape 3: Installer Poetry
RUN pip install poetry

# Étape 4: Copier les fichiers de configuration de Poetry
COPY pyproject.toml poetry.lock* /opt/airflow/

# Étape 5: Installer les dépendances sans créer d'environnement virtuel
RUN poetry config virtualenvs.create false && poetry install --no-root --only=main

# Étape 6: Copier le reste des fichiers du projet
COPY .. /opt/airflow

RUN python setup.py install
RUN pip install --upgrade typing_extensions typeguard

# Copier le script d'initialisation et le rendre exécutable
COPY airflow-docker/init_script.sh /opt/airflow/
RUN chmod +x /opt/airflow/init_script.sh

# Définir les variables d'environnement nécessaires pour Airflow
ENV AIRFLOW_HOME=/opt/airflow/velib_forecasting/ETL/
ENV AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/velib_forecasting/ETL/dags/
ENV AIRFLOW__CORE__EXECUTOR=SequentialExecutor
ENV AIRFLOW__CORE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
ENV AIRFLOW__CORE__LOAD_EXAMPLES=False
ENV AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db

RUN airflow db init
# Exposer le port par défaut du serveur web Airflow

RUN airflow users create \
    --username admin \
    --firstname HIPPOLYTE \
    --lastname GUIGON \
    --role Admin \
    --email hippodouche@me.com \
    --password Mogalys900


EXPOSE 8080

# Étape finale: Définir la commande par défaut pour exécuter le script d'initialisation
CMD ["/opt/airflow/init_script.sh"]
