version: 2.1
orbs:
  python: circleci/python@2
jobs:
  test-python:
    docker:
      - image: cimg/python:3.9  # Image de base avec Python 3.9
    steps:
      - checkout  # Récupérer le code source

      - run:
          name: Nettoyer le cache Poetry
          command: poetry cache clear --all pypi  # Nettoyer le cache Poetry

      - python/install-packages:
          pkg-manager: poetry  # Installer les dépendances définies dans pyproject.toml

      - run:
          name: Installer pytest
          command: poetry add pytest  # Installer explicitement pytest pour s'assurer de sa présence

      - run:
          name: Exécuter les tests avec pytest
          command: poetry run pytest test_unnitest.py --junitxml=junit.xml  # Exécuter le fichier de test spécifique

      - store_test_results:
          path: junit.xml  # Stocker les résultats des tests
workflows:
  build-and-test:
    jobs:
      - test-python
