version: 2.1
orbs:
  python: circleci/python@2
jobs:
  test-python:
    docker:
      - image: cimg/python:3.9  # Image de base avec Python 3.9
    steps:
      - checkout  # Récupérer le code source

      - run:
          name: Installer les dépendances avec pip
          command: pip install -r requirements.txt  # Installer les dépendances avec pip

      - run:
          name: Exécuter les tests avec pytest
          command: python -m pytest test_unnitest.py --junitxml=junit.xml  # Exécuter le fichier de test spécifique

      - store_test_results:
          path: junit.xml  # Stocker les résultats des tests
workflows:
  build-and-test:
    jobs:
      - test-python
