version: 2.1
orbs:
  python: circleci/python@2  # Utilisation de l'orbe Python de CircleCI
jobs:
  test-python:
    docker:
      - image: cimg/python:3.9  # Utilise Python 3.9 comme base d'image
    steps:
      - checkout  # Récupérer le code source

      - run:
          name: Installer les dépendances avec pip
          command: pip install -r requirements.txt  # Installer les dépendances définies dans requirements.txt

      - run:
          name: Exécuter les tests avec pytest
          command: python -m pytest test_unnitest.py --junitxml=junit.xml  # Exécuter les tests avec pytest

      - store_test_results:
          path: junit.xml  # Stocker les résultats des tests unitaires

  deploy:
    docker:
      - image: google/cloud-sdk:latest  # Image avec gcloud
    environment:
      CLOUDSDK_CORE_PROJECT: velib-forecasting  # Définit le projet Google Cloud
    steps:
      - checkout  # Récupérer le code source

      - run:
          name: Exécuter Cloud Build pour le déploiement
          command: gcloud builds submit --config=cloudbuild.yaml  # Exécuter Cloud Build avec le fichier de configuration

workflows:
  ci-cd:
    jobs:
      - test-python
      - deploy:
          requires: [test-python]  # Ne s'exécute que si le test-python réussit
