version: 2.1
orbs:
  python: circleci/python@2
jobs:
  test-python:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Régénérer le fichier poetry.lock
          command: poetry lock --no-update
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Exécuter les tests avec pytest
          command: poetry run pytest test_unnitest.py --junitxml=junit.xml || ((($? == 5)) && echo 'Did not find any tests to run.')
      - store_test_results:
          path: junit.xml
workflows:
  build-and-test:
    jobs:
      - test-python
