version: 2.1
orbs:
  python: circleci/python@2
jobs:
  test-python:
    docker:
      - image: cimg/python:3.9  # Image de base avec Python 3.9
    steps:
      - checkout  # Récupérer le code source

      - run:
          name: Installer les dépendances avec pip
          command: pip install -r requirements.txt  # Installer les dépendances

      - run:
          name: Exécuter les tests avec pytest
          command: python -m pytest test_unnitest.py --junitxml=junit.xml  # Exécuter les tests unitaires

      - store_test_results:
          path: junit.xml  # Stocker les résultats des tests unitaires

  trigger-and-get-build-id:
    docker:
      - image: google/cloud-sdk:latest  # Image avec gcloud
    environment:
      CLOUDSDK_CORE_PROJECT: velib-forecasting  # Définir le projet Google Cloud
      GOOGLE_APPLICATION_CREDENTIALS: ./velib-forecasting-auth.json  # Chemin vers la clé de service
    steps:
      - checkout  # Récupérer le code source

      - run:
          name: Authentification Google Cloud
          command: gcloud auth activate-service-account --key-file $GOOGLE_APPLICATION_CREDENTIALS  # Authentification

      - run:
          name: Déclencher le Trigger Cloud Build
          command: |
            gcloud builds triggers run bf9e3d60-bed9-4322-a21a-ea854bd5cba8  # Déclenche le trigger
            sleep 5  # Attendre 5 secondes pour permettre au build de démarrer

      - run:
          name: Obtenir le Build ID le Plus Récent
          command: |
            BUILD_ID=$(gcloud builds list --sort-by='~createTime' --limit=1 --format='value(id)')  # Obtenir le build_id le plus récent
            echo "BUILD_ID: $BUILD_ID"
            echo $BUILD_ID > build_id.txt  # Enregistrer le BUILD_ID

      - run:
          name: Surveiller le Build Cloud Build
          command: |
            BUILD_ID=$(cat build_id.txt)  # Lire le BUILD_ID
            STATUS=""
            while [[ "$STATUS" != "SUCCESS" && "$STATUS" != "FAILURE" ]]; faites
              STATUS=$(gcloud builds describe $BUILD_ID --format='value(status)')  # Obtenir le statut du build
              echo "Statut du Build: $STATUS"
              sleep 10  # Pause avant de vérifier à nouveau
            done
            if [ "$STATUS" = "FAILURE" ]; then
              echo "Le Build a échoué"
              exit 1  # Arrêter si le build échoue
            fi

workflows:
  ci-cd:
    jobs:
      - test-python
      - trigger-and-get-build-id:
          requires: [test-python]  # Exécution après le succès des tests unitaires
