velib_dbt_project:
  outputs:
    dev:
      dataset: velib_info
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: velib-forecasting-auth.json
      location: europe-west1
      method: service-account
      priority: interactive
      project: velib-forecasting
      threads: 1
      type: bigquery
  target: dev
velib_forecasting_dbt:
  outputs:
    dev:
      dataset: dbt_dataset
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: velib-forecasting-auth.json
      location: europe-west1
      method: service-account
      priority: interactive
      project: velib-forecasting
      threads: 4
      type: bigquery
  target: dev
velib_forecasting_dbt_project:
  outputs:
    dev:
      dataset: dbt_dataset
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: velib-forecasting-auth.json
      location: EU
      method: service-account
      priority: interactive
      project: velib-forecasting
      threads: 4
      type: bigquery
  target: dev
