# Utiliser une image de base avec Python
FROM python:3.9-slim

# Installer les dépendances système nécessaires
RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    && rm -rf /var/lib/apt/lists/*

# Installer MLflow et d'autres dépendances Python nécessaires
RUN pip install mlflow[extras] sqlalchemy

# Créer un répertoire de travail
WORKDIR /app

# Spécifier la commande pour démarrer MLflow
CMD ["mlflow", "server", "--backend-store-uri", "sqlite:///mlflow.db", "--default-artifact-root", "/mlflow/artifacts", "--host", "0.0.0.0"]
