FROM python:3.8-slim

RUN apt-get update && apt-get install -y git

WORKDIR /app

COPY velib_forecasting/mlflow_deployment/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY .. .

RUN python setup.py install

CMD ["python", "velib_forecasting/mlflow_deployment/mlflow_pipeline.py"]
