FROM python:3.9-slim-buster

WORKDIR /opt/airflow

RUN pip install apache-airflow==2.3.0 --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.3.0/constraints-3.9.txt"

COPY . /opt/airflow

RUN pip install -r requirements.txt
RUN python setup.py install
RUN pip install --upgrade typing_extensions typeguard

RUN pip install pendulum==2.1.2
RUN pip install mysql-connector-python

ENV AIRFLOW_HOME=/opt/airflow/velib_forecasting/ETL/
ENV AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/velib_forecasting/ETL/dags/
ENV AIRFLOW__CORE__EXECUTOR=LocalExecutor
ENV AIRFLOW__CORE__SQL_ALCHEMY_CONN=mysql+mysqlconnector://airflow_user:Mogalys900@mysql-service:3306/airflow_db
ENV AIRFLOW__CORE__LOAD_EXAMPLES=False
ENV AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=mysql+mysqlconnector://airflow_user:Mogalys900@mysql-service:3306/airflow_db
ENV AIRFLOW__SCHEDULER__SCHEDULER_RUNS=True
ENV AIRFLOW__WEBSERVER__SESSION_BACKEND=securecookie

EXPOSE 8080

CMD ["airflow", "webserver"]
