apiVersion: v1
kind: Service
metadata:
  name: velib-forecasting-service
spec:
  selector:
    app: velib-forecasting
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
