name: Sync DAGs to Cloud Composer

on:
  push:
    branches:
      - main  # Ou votre branche de développement

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Sync DAGs to GCS
      run: gsutil rsync -r velib_forecasting/ETL gs://airflow-bucket-storage/dags/
